/**
 * Word List for Word Guess Game
 * Answer words: curated common English words by length (4-8 letters)
 * Guess validation: Free Dictionary API + local cache
 */

// Difficulty tier configuration
const DIFFICULTY_TIERS = {
    easy:   { minLen: 4, maxLen: 5, maxGuesses: 8, label: 'Easy' },
    normal: { minLen: 5, maxLen: 6, maxGuesses: 6, label: 'Normal' },
    hard:   { minLen: 6, maxLen: 7, maxGuesses: 5, label: 'Hard' },
    expert: { minLen: 7, maxLen: 8, maxGuesses: 4, label: 'Expert' }
};

// 4-letter words
const WORDS_4 = [
    'ABLE','ALSO','AREA','ARMY','AWAY','BACK','BALL','BAND','BANK','BASE',
    'BATH','BEAN','BEAR','BEAT','BEEN','BELL','BELT','BEND','BEST','BIKE',
    'BIRD','BITE','BLOW','BLUE','BOAT','BODY','BOLD','BOMB','BOND','BONE',
    'BOOK','BOOT','BORN','BOSS','BOTH','BOWL','BULK','BURN','BURY','BUSH',
    'BUSY','CAFE','CAGE','CAKE','CALL','CALM','CAME','CAMP','CARD','CARE',
    'CART','CASE','CASH','CAST','CAVE','CELL','CHAT','CHIP','CITY','CLAP',
    'CLAY','CLIP','CLUB','CLUE','COAL','COAT','CODE','COIN','COLD','COME',
    'COOK','COOL','COPE','COPY','CORD','CORE','CORN','COST','CREW','CROP',
    'CROW','CURE','CURL','CUTE','DALE','DAME','DAMN','DAMP','DARE','DARK',
    'DART','DASH','DATA','DATE','DAWN','DEAD','DEAF','DEAL','DEAR','DEBT',
    'DECK','DEED','DEEM','DEEP','DEER','DEMO','DENY','DESK','DIAL','DIET',
    'DIRT','DISC','DISH','DISK','DOCK','DOES','DONE','DOOM','DOOR','DOSE',
    'DOWN','DRAG','DRAW','DREW','DROP','DRUG','DRUM','DUAL','DUCK','DUDE',
    'DUEL','DUKE','DULL','DUMB','DUMP','DUNE','DUST','DUTY','EACH','EARN',
    'EASE','EAST','EASY','EDGE','EDIT','ELSE','EMIT','ENVY','EPIC','EVEN',
    'EVER','EVIL','EXAM','EXIT','FACE','FACT','FADE','FAIL','FAIR','FAKE',
    'FALL','FAME','FANG','FARE','FARM','FAST','FATE','FEAR','FEAT','FEED',
    'FEEL','FELL','FELT','FILE','FILL','FILM','FIND','FINE','FIRE','FIRM',
    'FISH','FIST','FLAG','FLAT','FLED','FLEW','FLIP','FLOW','FOAM','FOIL',
    'FOLD','FOLK','FOND','FONT','FOOD','FOOL','FOOT','FORD','FORE','FORK',
    'FORM','FORT','FOUL','FOUR','FREE','FROM','FUEL','FULL','FUND','FURY',
    'FUSE','GAIN','GALE','GAME','GANG','GATE','GAVE','GAZE','GEAR','GENE',
    'GIFT','GIRL','GIVE','GLAD','GLOW','GLUE','GOAL','GOAT','GOES','GOLD',
    'GOLF','GONE','GOOD','GRAB','GRAY','GREW','GRID','GRIN','GRIP','GROW',
    'GULF','GURU','GUST','HACK','HAIL','HAIR','HALF','HALL','HALT','HAND',
    'HANG','HARD','HARM','HATE','HAUL','HAVE','HEAD','HEAL','HEAP','HEAR',
    'HEAT','HEEL','HELD','HELL','HELP','HERE','HERO','HIGH','HIKE','HILL',
    'HINT','HIRE','HOLD','HOLE','HOME','HOOD','HOOK','HOPE','HORN','HOST',
    'HUGE','HULL','HUNG','HUNT','HURT','HYMN','ICON','IDEA','INCH','INTO',
    'IRON','ISLE','ITEM','JACK','JAIL','JAZZ','JEAN','JERK','JEST','JOBS',
    'JOIN','JOKE','JUMP','JUNE','JURY','JUST','KEEN','KEEP','KEPT','KICK',
    'KIDS','KILL','KIND','KING','KISS','KITE','KNEE','KNEW','KNIT','KNOB',
    'KNOT','KNOW','LACE','LACK','LAID','LAKE','LAMP','LAND','LANE','LAPS',
    'LAST','LATE','LAWN','LEAD','LEAF','LEAK','LEAN','LEAP','LEFT','LEND',
    'LENS','LESS','LIAR','LIFE','LIFT','LIKE','LIMB','LIME','LINE','LINK',
    'LION','LIST','LIVE','LOAD','LOAN','LOCK','LOGO','LONG','LOOK','LOOP',
    'LORD','LOSE','LOSS','LOST','LOTS','LOUD','LOVE','LUCK','LUMP','LUNG',
    'LURE','LURK','LUSH','MAID','MAIL','MAIN','MAKE','MALE','MALL','MALT',
    'MANE','MANY','MAPS','MARK','MARS','MASK','MASS','MATE','MAZE','MEAL',
    'MEAN','MEAT','MEET','MELT','MEMO','MENU','MERE','MESH','MESS','MILD',
    'MILK','MILL','MIND','MINE','MINT','MISS','MODE','MOLD','MOOD','MOON',
    'MORE','MOSS','MOST','MOTH','MOVE','MUCH','MUSE','MUST','MYTH','NAIL',
    'NAME','NAVY','NEAR','NEAT','NECK','NEED','NEST','NEWS','NEXT','NICE',
    'NINE','NODE','NONE','NORM','NOSE','NOTE','NOUN','ODDS','OKAY','ONCE',
    'ONLY','ONTO','OPEN','OPTS','ORAL','OVEN','OVER','PACE','PACK','PAGE',
    'PAID','PAIN','PAIR','PALE','PALM','PANE','PARK','PART','PASS','PAST',
    'PATH','PEAK','PEEL','PEER','PICK','PINE','PINK','PIPE','PLAN','PLAY',
    'PLEA','PLOT','PLUG','PLUS','POEM','POET','POKE','POLE','POLL','POND',
    'POOL','POOR','POPE','PORK','PORT','POSE','POST','POUR','PRAY','PREY',
    'PROP','PULL','PULP','PUMP','PURE','PUSH','QUIT','QUIZ','RACE','RACK',
    'RAGE','RAID','RAIL','RAIN','RANK','RARE','RATE','READ','REAL','REAR',
    'REEF','REIN','RELY','RENT','REST','RICE','RICH','RIDE','RING','RIOT',
    'RISE','RISK','ROAD','ROAM','ROCK','RODE','ROLE','ROLL','ROOF','ROOM',
    'ROOT','ROPE','ROSE','RUIN','RULE','RUSH','RUST','SAFE','SAGA','SAGE',
    'SAID','SAIL','SAKE','SALE','SALT','SAME','SAND','SANG','SANK','SAVE',
    'SCAN','SEAL','SEAM','SEAT','SECT','SEED','SEEK','SEEM','SEEN','SELF',
    'SELL','SEND','SENT','SHED','SHIN','SHIP','SHOP','SHOT','SHOW','SHUT',
    'SICK','SIDE','SIGH','SIGN','SILK','SING','SINK','SITE','SIZE','SKIN',
    'SKIP','SLAM','SLAP','SLIM','SLIP','SLOT','SLOW','SNAP','SNOW','SOAK',
    'SOAP','SOCK','SOFA','SOFT','SOIL','SOLD','SOLE','SOME','SONG','SOON',
    'SORT','SOUL','SOUR','SPAN','SPIN','SPOT','STAR','STAY','STEM','STEP',
    'STEW','STOP','STUN','SUCH','SUIT','SURE','SURF','SWAN','SWAP','SWIM',
    'TAIL','TAKE','TALE','TALK','TALL','TANK','TAPE','TASK','TAXI','TEAM',
    'TEAR','TELL','TEMP','TEND','TENT','TERM','TEST','TEXT','THAN','THAT',
    'THEM','THEN','THEY','THIN','THIS','THUS','TICK','TIDE','TIDY','TIED',
    'TIER','TILE','TILL','TILT','TIME','TINY','TIRE','TOAD','TOLD','TOLL',
    'TOMB','TONE','TOOK','TOOL','TOPS','TORE','TORN','TOSS','TOUR','TOWN',
    'TRAP','TRAY','TREE','TRIM','TRIO','TRIP','TRUE','TUBE','TUCK','TUNA',
    'TUNE','TURN','TWIN','TYPE','TYRE','UGLY','UNDO','UNIT','UPON','URGE',
    'USED','USER','VAIN','VALE','VARY','VASE','VAST','VEIL','VEIN','VENT',
    'VERB','VERY','VEST','VETO','VICE','VIEW','VINE','VISA','VOID','VOLT',
    'VOTE','WADE','WAGE','WAIL','WAIT','WAKE','WALK','WALL','WAND','WANT',
    'WARD','WARM','WARN','WARP','WARS','WASH','WAVE','WAVY','WAXY','WEAK',
    'WEAR','WEED','WEEK','WELL','WENT','WERE','WEST','WHAT','WHEN','WHOM',
    'WIDE','WIFE','WILD','WILL','WILT','WIND','WINE','WING','WINK','WIPE',
    'WIRE','WISE','WISH','WITH','WOKE','WOLF','WOOD','WOOL','WORD','WORE',
    'WORK','WORM','WORN','WRAP','WRIT','YARD','YARN','YEAR','YELL','YOUR',
    'ZEAL','ZERO','ZINC','ZONE','ZOOM'
];

// Answer words: common, well-known 5-letter words for daily/practice puzzles
const WORDS_5 = [
    // A
    'ABOUT','ABOVE','ABUSE','ACTOR','ACUTE','ADMIT','ADOPT','ADULT','AFTER','AGAIN',
    'AGENT','AGREE','AHEAD','ALARM','ALBUM','ALERT','ALIEN','ALIGN','ALIKE','ALIVE',
    'ALLEY','ALLOW','ALONE','ALONG','ALTER','AMAZE','AMBER','AMONG','AMPLE','ANGEL',
    'ANGER','ANGLE','ANGRY','ANKLE','ANNOY','APART','APPLE','APPLY','ARENA','ARGUE',
    'ARISE','ARMOR','AROMA','ARRAY','ARROW','ASIDE','ASSET','ATTIC','AUDIO','AUDIT',
    'AVOID','AWAKE','AWARD','AWARE',
    // B
    'BADGE','BADLY','BAKER','BASIC','BASIN','BASIS','BATCH','BEACH','BEARS','BEAST',
    'BEGAN','BEGIN','BEING','BELOW','BENCH','BERRY','BLACK','BLADE','BLAME','BLANK',
    'BLAST','BLAZE','BLEED','BLEND','BLESS','BLIND','BLINK','BLISS','BLOCK','BLOOD',
    'BLOOM','BLOWN','BLUES','BOARD','BOATS','BONES','BONUS','BOOKS','BOOST','BOOTH',
    'BOUND','BRAIN','BRAND','BRASS','BRAVE','BREAD','BREAK','BREED','BRICK','BRIDE',
    'BRIEF','BRING','BROAD','BROKE','BROOK','BROWN','BRUSH','BUILD','BUILT','BUNCH',
    'BURST','BUYER',
    // C
    'CABIN','CABLE','CAMEL','CANDY','CARDS','CARGO','CARRY','CATCH','CAUSE','CEASE',
    'CHAIN','CHAIR','CHALK','CHAMP','CHAOS','CHARM','CHART','CHASE','CHEAP','CHEAT',
    'CHECK','CHEEK','CHEER','CHESS','CHEST','CHIEF','CHILD','CHILL','CHINA','CHOIR',
    'CHOSE','CHUNK','CIVIC','CIVIL','CLAIM','CLASH','CLASS','CLEAN','CLEAR','CLERK',
    'CLICK','CLIFF','CLIMB','CLING','CLOCK','CLONE','CLOSE','CLOTH','CLOUD','CLOWN',
    'CLUBS','CLUES','COACH','COAST','CODES','COMET','COMIC','CORAL','COUNT','COUCH',
    'COULD','COURT','COVER','CRACK','CRAFT','CRANE','CRASH','CRAZE','CRAZY','CREAM',
    'CREEK','CREST','CRIME','CRISP','CROSS','CROWD','CROWN','CRUDE','CRUEL','CRUSH',
    'CURVE','CYCLE',
    // D
    'DAILY','DAIRY','DANCE','DEATH','DEALT','DEBUG','DECAY','DEMON','DENSE','DEPTH',
    'DERBY','DEVIL','DIARY','DIGIT','DIRTY','DODGE','DOUBT','DOUGH','DRAFT','DRAIN',
    'DRAMA','DRANK','DRAWN','DREAM','DRESS','DRIED','DRIFT','DRILL','DRINK','DRIVE',
    'DROPS','DROVE','DROWN','DRUNK','DWARF','DYING',
    // E
    'EAGER','EAGLE','EARLY','EARTH','EIGHT','ELBOW','ELDER','ELECT','ELITE','EMPTY',
    'ENEMY','ENJOY','ENTER','EQUAL','EQUIP','ERROR','EVENT','EVERY','EXACT','EXAMS',
    'EXIST','EXTRA',
    // F
    'FABLE','FAITH','FALSE','FANCY','FATAL','FAULT','FEAST','FENCE','FEWER','FIBER',
    'FIELD','FIFTH','FIFTY','FIGHT','FINAL','FIRST','FIXED','FLAME','FLASH','FLESH',
    'FLOAT','FLOOD','FLOOR','FLOUR','FLUID','FLUSH','FLUTE','FOCUS','FORCE','FORGE',
    'FORTY','FORUM','FOUND','FRAME','FRANK','FRAUD','FRESH','FRONT','FROST','FROZE',
    'FRUIT','FULLY','FUNDS','FUNNY','FUZZY',
    // G
    'GIANT','GIVEN','GLASS','GLEAM','GLOBE','GLOOM','GLORY','GLOSS','GLOVE','GOING',
    'GRACE','GRADE','GRAIN','GRAND','GRANT','GRAPE','GRAPH','GRASP','GRASS','GRAVE',
    'GRAVY','GREAT','GREED','GREEN','GREET','GRIEF','GRILL','GRIND','GROAN','GROSS',
    'GROUP','GROVE','GROWN','GUARD','GUESS','GUEST','GUIDE','GUILT','GUISE','GUMMY',
    // H
    'HABIT','HANDS','HAPPY','HARDY','HARSH','HASTE','HAUNT','HAVEN','HEADS','HEARD',
    'HEART','HEAVY','HELLO','HERBS','HERON','HINTS','HOBBY','HONEY','HONOR','HORSE',
    'HOTEL','HOURS','HOUSE','HOVER','HUMAN','HUMOR','HURRY',
    // I
    'IDEAL','IMAGE','IMPLY','INDEX','INDIE','INNER','INPUT','IRONY','ISSUE','IVORY',
    // J
    'JEWEL','JOINT','JOKER','JOLLY','JUDGE','JUICE','JUICY','JUMBO',
    // K
    'KAYAK','KNACK','KNEEL','KNIFE','KNOCK','KNOWN',
    // L
    'LABEL','LABOR','LANCE','LARGE','LASER','LATER','LAUGH','LAYER','LEADS','LEARN',
    'LEASE','LEAST','LEGAL','LEMON','LEVEL','LEVER','LIGHT','LIMIT','LINEN','LIVER',
    'LLAMA','LOCAL','LODGE','LOGIC','LOOSE','LORRY','LOVER','LOWER','LOYAL','LUCKY',
    'LUNAR','LUNCH','LYING',
    // M
    'MAGIC','MAJOR','MAKER','MANGA','MANOR','MAPLE','MARCH','MATCH','MAYOR','MEDIA',
    'MELON','MERCY','MERGE','MERIT','MERRY','METAL','METER','MIGHT','MINER','MINOR',
    'MINUS','MIRTH','MODEL','MONEY','MONTH','MORAL','MOTOR','MOUND','MOUNT','MOUSE',
    'MOUTH','MOVED','MOVIE','MUDDY','MUSIC','MOOSE',
    // N
    'NAIVE','NAKED','NASTY','NAVAL','NERVE','NEVER','NEWLY','NEXUS','NIGHT','NOBLE',
    'NOISE','NORTH','NOTED','NOVEL','NURSE',
    // O
    'OASIS','OCCUR','OCEAN','OFFER','OFTEN','OLIVE','ONSET','OPERA','ORBIT','ORDER',
    'OTHER','OUGHT','OUTER','OWNER','OXIDE',
    // P
    'PAINT','PANEL','PANIC','PAPER','PARTY','PASTA','PATCH','PAUSE','PEACE','PEACH',
    'PEARL','PENNY','PHASE','PHONE','PHOTO','PIANO','PIECE','PILOT','PINCH','PITCH',
    'PIXEL','PIZZA','PLACE','PLAIN','PLANE','PLANT','PLATE','PLAZA','PLEAD','PLUCK',
    'PLUMB','PLUME','PLUMP','POINT','POLAR','POUND','POWER','PRESS','PRICE','PRIDE',
    'PRIME','PRINT','PRIOR','PRIZE','PROBE','PROOF','PROUD','PROVE','PROXY','PULSE',
    'PUNCH','PUPIL','PURSE',
    // Q
    'QUACK','QUEEN','QUERY','QUEST','QUEUE','QUICK','QUIET','QUILT','QUIRK','QUITE',
    'QUOTA','QUOTE',
    // R
    'RADAR','RADIO','RAISE','RALLY','RANCH','RANGE','RAPID','RATIO','REACH','REACT',
    'READY','REALM','REBEL','REIGN','RELAX','RELAY','RENAL','RENEW','REPLY','RIDER',
    'RIDGE','RIFLE','RIGHT','RIGID','RISEN','RISKY','RIVAL','RIVER','ROBIN','ROBOT',
    'ROCKY','ROGER','ROUGE','ROUGH','ROUND','ROUTE','ROYAL','RUGBY','RULER','RURAL',
    // S
    'SADLY','SAINT','SALAD','SAUCE','SCALE','SCARE','SCARY','SCENE','SCENT','SCORE',
    'SCOUT','SCRAP','SEIZE','SENSE','SERVE','SEVEN','SHADE','SHALL','SHAME','SHAPE',
    'SHARE','SHARK','SHARP','SHAVE','SHEEP','SHEER','SHEET','SHELF','SHELL','SHIFT',
    'SHINE','SHIRT','SHOCK','SHOOT','SHORE','SHORT','SHOUT','SHOWN','SIGHT','SILLY',
    'SINCE','SIXTH','SIXTY','SKILL','SKULL','SLASH','SLATE','SLEEP','SLICE','SLIDE',
    'SLOPE','SMART','SMELL','SMILE','SMOKE','SNAKE','SOLAR','SOLID','SOLVE','SORRY',
    'SOUTH','SPACE','SPARE','SPARK','SPEAK','SPEED','SPELL','SPEND','SPENT','SPICE',
    'SPIKE','SPINE','SPLIT','SPOKE','SPOON','SPORT','SPRAY','SQUAD','STAGE','STAIN',
    'STAKE','STALE','STALK','STALL','STAMP','STAND','STARE','START','STATE','STEAK',
    'STEAL','STEAM','STEEL','STEEP','STEER','STERN','STICK','STIFF','STILL','STOCK',
    'STOLE','STONE','STOOD','STOOL','STORE','STORM','STORY','STOVE','STUCK','STUDY',
    'STUFF','STUMP','STUNG','STYLE','SUGAR','SUITE','SUNNY','SUPER','SURGE','SWAMP',
    'SWEAR','SWEAT','SWEEP','SWEET','SWEPT','SWIFT','SWING','SWORD','SWORE','SWORN',
    // T
    'TABLE','TASTE','TEACH','TEETH','TEMPO','TENSE','TENTH','TERMS','THEFT','THEME',
    'THERE','THICK','THIEF','THING','THINK','THIRD','THORN','THOSE','THREE','THREW',
    'THROW','THUMB','TIGER','TIGHT','TIMER','TIRED','TITLE','TODAY','TOKEN','TOTAL',
    'TOUCH','TOUGH','TOWER','TOXIC','TRACE','TRACK','TRADE','TRAIL','TRAIN','TRAIT',
    'TRASH','TREAT','TREND','TRIAL','TRIBE','TRICK','TRIED','TROOP','TRUCK','TRULY',
    'TRUMP','TRUNK','TRUST','TRUTH','TUMOR','TUNER','TURNS','TWICE','TWIST',
    // U
    'ULTRA','UNCLE','UNDER','UNION','UNITE','UNITY','UNTIL','UPPER','UPSET','URBAN',
    'USAGE','USUAL','UTTER',
    // V
    'VAGUE','VALID','VALUE','VALVE','VAULT','VIDEO','VIGOR','VINYL','VIRAL','VIRUS',
    'VISIT','VITAL','VIVID','VOCAL','VODKA','VOICE','VOTER',
    // W
    'WAGES','WAGON','WAIST','WASTE','WATCH','WATER','WAVES','WEARY','WEAVE','WEDGE',
    'WEIRD','WHALE','WHEAT','WHEEL','WHERE','WHICH','WHILE','WHITE','WHOLE','WHOSE',
    'WIDER','WIDTH','WITCH','WOMAN','WOMEN','WOODS','WORLD','WORRY','WORSE','WORST',
    'WORTH','WOULD','WOUND','WRATH','WRITE','WRONG','WROTE',
    // Y
    'YACHT','YIELD','YOUNG','YOUTH',
    // Z
    'ZEBRA','ZESTY'
];

// 6-letter words
const WORDS_6 = [
    'ABSORB','ACCEPT','ACCESS','ACROSS','ACTION','ACTIVE','ACTUAL','ADVENT','ADVICE',
    'ADVISE','AFFAIR','AFFECT','AFFORD','AGENDA','AGENTS','AGREED','ALMOST','ALWAYS',
    'AMOUNT','ANIMAL','ANNUAL','ANSWER','ANYONE','ANYWAY','APPEAL','APPEAR','AROUND',
    'ARRIVE','ARTIST','ASKING','ASSERT','ASSESS','ASSIGN','ASSIST','ASSUME','ATTACK',
    'ATTEND','AUGUST','AUTUMN','BACKER','BARELY','BARREL','BASKET','BATTLE','BEAUTY',
    'BECAME','BECOME','BEFORE','BEHALF','BEHIND','BELIEF','BELONG','BERLIN','BESIDE',
    'BETTER','BEYOND','BISHOP','BITTER','BLANCH','BLOODY','BORDER','BOTHER','BOTTOM',
    'BOUNCE','BRANCH','BREATH','BRIDGE','BRIGHT','BROKEN','BROKER','BRONZE','BUBBLE',
    'BUCKET','BUDGET','BUFFER','BULLET','BUNDLE','BURDEN','BUREAU','BURGER','BUTTON',
    'BUYING','CABINET','CALLED','CAMERA','CANCEL','CARBON','CAREER','CASTLE','CASUAL',
    'CAUGHT','CAUSED','CENTRE','CHANCE','CHANGE','CHARGE','CHOSEN','CHURCH','CIRCLE',
    'CLIENT','CLOSED','CLOSER','CLOTHE','COFFEE','COLONY','COLUMN','COMBAT','COMING',
    'COMMON','COMPLY','CORNER','COSTLY','COTTON','COUPLE','COURSE','COUSIN','CREATE',
    'CREDIT','CRISIS','CUSTOM','DAMAGE','DANGER','DEBATE','DECADE','DECIDE','DEFEAT',
    'DEFEND','DEFINE','DEGREE','DEMAND','DENIAL','DEPEND','DEPLOY','DEPUTY','DERIVE',
    'DESERT','DESIGN','DESIRE','DETECT','DEVICE','DEVOTE','DIFFER','DINNER','DIRECT',
    'DIVINE','DOCTOR','DOMAIN','DOUBLE','DRIVER','DURING','EARNED','EASILY','EATING',
    'EDITOR','EFFECT','EFFORT','EIGHTH','ELEVEN','EMERGE','EMPIRE','EMPLOY','ENABLE',
    'ENDING','ENERGY','ENGAGE','ENGINE','ENJOY','ENOUGH','ENSURE','ENTIRE','ENTITY',
    'EQUITY','ESCAPE','ESTATE','ETHNIC','EVOLVE','EXCEED','EXCEPT','EXCITE','EXCUSE',
    'EXEMPT','EXPAND','EXPECT','EXPERT','EXPORT','EXPOSE','EXTEND','EXTENT','FABRIC',
    'FACIAL','FACTOR','FAIRLY','FALLEN','FAMILY','FAMOUS','FARMER','FATHER','FAUCET',
    'FELLOW','FEMALE','FIERCE','FIGURE','FILTER','FINALE','FINGER','FINISH','FISCAL',
    'FLIGHT','FLOWER','FLYING','FOLLOW','FOREST','FOREVER','FORGET','FORMAL','FORMAT',
    'FORMER','FOSSIL','FOSTER','FOURTH','FREELY','FREEZE','FRENCH','FRIEND','FROZEN',
    'FULFIL','FUNDED','FUTURE','GAINED','GALAXY','GAMBLE','GARDEN','GATHER','GENDER',
    'GENTLE','GIFTED','GLOBAL','GOLDEN','GOVERN','GRAVEL','GROWTH','GUIDED','GUITAR',
    'HANDLE','HAPPEN','HARDLY','HAZARD','HEADER','HEALTH','HELPED','HEREBY','HIGHLY',
    'HOLDER','HONEST','HORROR','HOSTED','HUNGER','HUNTER','IGNORE','IMPACT','IMPORT',
    'IMPOSE','INCOME','INDEED','INDOOR','INFANT','INFORM','INJURY','INLAND','INSECT',
    'INSERT','INSIDE','INSIST','INTACT','INTEND','INTENT','INVEST','INVITE','ISLAND',
    'ITSELF','JACKET','JUNGLE','JUNIOR','LAUNCH','LAWYER','LAYOUT','LEADER','LEAGUE',
    'LENDER','LENGTH','LESSON','LETTER','LIABLE','LIKELY','LINEAR','LINKED','LIQUOR',
    'LISTEN','LIVELY','LIVING','LOCATE','LONELY','LOOKUP','LUXURY','MAINLY','MANAGE',
    'MANNER','MARGIN','MARINE','MARKED','MARKET','MASTER','MATTER','MATURE','MEDIUM',
    'MEMBER','MEMORY','MENTAL','MENTOR','METHOD','MIDDLE','MIGHTY','MILLER','MINUTE',
    'MIRROR','MOBILE','MODERN','MODEST','MOMENT','MOTHER','MOTION','MOVING','MURDER',
    'MUSEUM','MUTUAL','MYSELF','NAMELY','NARROW','NATION','NATIVE','NATURE','NEARBY',
    'NEARLY','NEATLY','NEEDED','NICELY','NOBODY','NORMAL','NOTICE','NOTION','NOVICE',
    'NUMBER','OBJECT','OBTAIN','OCCUPY','OFFEND','OFFICE','ONLINE','OPENER','OPPOSE',
    'OPTION','ORANGE','ORIGIN','OUTPUT','OXFORD','OXYGEN','PACKED','PALACE','PARENT',
    'PARTLY','PATENT','PATROL','PATRON','PATTER','PENCIL','PEOPLE','PERIOD','PERMIT',
    'PERSON','PHRASE','PICKED','PILLAR','PLANET','PLAYER','PLEASE','PLEDGE','PLENTY',
    'POCKET','POETRY','POISON','POLICE','POLICY','POLITE','POORLY','POSTER','POTATO',
    'POWDER','PRAYER','PREFIX','PRETTY','PRINCE','PRISON','PROFIT','PROPER','PROVEN',
    'PUBLIC','PUNISH','PURSUE','PUZZLE','RABBIT','RACIAL','RANDOM','RARELY','RATING',
    'READER','REALLY','REASON','RECALL','RECENT','RECORD','REDUCE','REFORM','REFUSE',
    'REGARD','REGIME','REGION','REJECT','RELATE','RELIEF','REMAIN','REMARK','REMEDY',
    'REMIND','REMOTE','REMOVE','RENDER','RENTAL','REPAIR','REPEAT','REPORT','RESCUE',
    'RESIGN','RESIST','RESORT','RESULT','RESUME','RETAIL','RETAIN','RETIRE','RETURN',
    'REVEAL','REVIEW','REVOLT','REWARD','RHYTHM','RIDING','RISING','RITUAL','ROBUST',
    'ROCKET','RULING','RUNNER','SAFELY','SAFETY','SALARY','SAMPLE','SAVING','SAYING',
    'SCHEME','SCHOOL','SCREEN','SCRIPT','SEARCH','SEASON','SECOND','SECRET','SECTOR',
    'SECURE','SELECT','SELLER','SENIOR','SERIAL','SERIES','SETTLE','SEVERE','SHADOW',
    'SHARED','SHIELD','SIGNAL','SILENT','SILVER','SIMPLE','SIMPLY','SINGER','SINGLE',
    'SISTER','SKETCH','SLIGHT','SMOOTH','SOCIAL','SOLELY','SOLVER','SOUGHT','SOURCE',
    'SPEECH','SPHERE','SPIRIT','SPREAD','SPRING','SQUARE','STABLE','STATUS','STEADY',
    'STOLEN','STRAIN','STRAND','STREAK','STREAM','STREET','STRESS','STRICT','STRIKE',
    'STRING','STROKE','STRONG','STUDIO','SUBMIT','SUBTLE','SUBURB','SUDDEN','SUFFER',
    'SUMMER','SUMMIT','SUPPLY','SURELY','SURVEY','SWITCH','SYMBOL','SYNTAX','SYSTEM',
    'TACKLE','TAILOR','TALENT','TARGET','TEMPLE','TENANT','TENDER','TERROR','THANKS',
    'THEORY','THREAT','THRIVE','THRONE','TIMBER','TISSUE','TONGUE','TOWARD','TRAVEL',
    'TREATY','TRIBAL','TRICKY','TROPHY','TUNNEL','TWELVE','TWENTY','UNFAIR','UNIQUE',
    'UNITED','UNLESS','UNLIKE','UNLOCK','UNREST','UPDATE','UPHOLD','UPTURN','URGENT',
    'USEFUL','VACANT','VALLEY','VARIED','VENDOR','VESSEL','VICTIM','VIEWER','VIOLET',
    'VIRGIN','VISION','VISUAL','VOLUME','VOTING','WANDER','WARMTH','WEALTH','WEAPON',
    'WEEKLY','WEIGHT','WIDELY','WILDLY','WINDOW','WINNER','WINTER','WISDOM','WITHIN',
    'WONDER','WORKER','WORTHY','WRITER','YEARLY','YELLOW','ZENITH'
];

// 7-letter words
const WORDS_7 = [
    'ABILITY','ABSENCE','ACADEMY','ACCOUNT','ACCUSED','ACHIEVE','ACQUIRE','ACTRESS',
    'ADAPTER','ADDRESS','ADOPTED','ADVANCE','ADVERSE','ADVISER','AIRLINE','ALCOHOL',
    'ALLEGED','ALREADY','ANCIENT','ANOTHER','ANXIETY','ANYMORE','ANYBODY','APPLIED',
    'ARRANGE','ARTICLE','ASSAULT','ATTEMPT','AUCTION','AUDITOR','BALANCE','BANKING',
    'BARGAIN','BARRIER','BATTERY','BEARING','BECAUSE','BEDROOM','BELIEVE','BENEFIT',
    'BESIDES','BIGGEST','BILLION','BINDING','BIZARRE','BLANKET','BLOCKED','BOOLEAN',
    'BREADTH','BREATHE','BRIEFLY','BROADER','BROADEN','BROUGHT','BROWSER','CABINET',
    'CABINET','CAUTION','CEILING','CERTAIN','CHAMBER','CHANNEL','CHAPTER','CHARITY',
    'CHARTER','CHEAPER','CHICKEN','CITIZEN','CLASSIC','CLIMATE','CLOSING','CLUSTER',
    'COASTAL','COLLECT','COLLEGE','COMBINE','COMFORT','COMMAND','COMMENT','COMPACT',
    'COMPANY','COMPARE','COMPETE','COMPLEX','CONCEPT','CONCERN','CONFIRM','CONNECT',
    'CONSENT','CONSULT','CONTACT','CONTAIN','CONTENT','CONTEST','CONTEXT','CONTROL',
    'CONVERT','COOLING','CORRECT','COUNCIL','COUNTER','COUNTRY','COURAGE','COVERED',
    'CRACKER','CREATED','CREATOR','CRICKET','CRIMSON','CRUSADE','CUISINE','CULTURE',
    'CURRENT','CURTAIN','CUSTOMS','CUTTING','DAMAGED','DEALING','DEBATED','DECLINE',
    'DEFAULT','DEFENCE','DEFICIT','DELAYED','DELIVER','DENSITY','DEPOSIT','DERIVED',
    'DESKTOP','DESPITE','DETAILS','DEVELOP','DEVOTED','DIAMOND','DIGITAL','DIPLOMA',
    'DISABLE','DISEASE','DISPLAY','DISPOSE','DISPUTE','DISTANT','DISTURB','DIVERSE',
    'DIVIDED','DIVORCE','DOCKING','DONATED','DOUBLED','DRAWING','DRESSED','DROPPED',
    'DYNAMIC','EARNEST','EASTERN','ECOLOGY','ECONOMY','EDITING','EDITION','ELDERLY',
    'ELECTED','ELEGANT','ELEMENT','ELEVATE','EMBRACE','EMOTION','EMPEROR','EMPRESS',
    'ENABLED','ENDLESS','ENFORCE','ENGAGED','ENGLISH','ENHANCE','ENQUIRY','EPISODE',
    'ESSENCE','ETERNAL','EVIDENT','EXACTLY','EXAMINE','EXAMPLE','EXCITED','EXCLUDE',
    'EXECUTE','EXHIBIT','EXPENSE','EXPLAIN','EXPLOIT','EXPLORE','EXPRESS','EXTREME',
    'FACTORY','FACULTY','FAILURE','FASHION','FATIGUE','FEATURE','FEDERAL','FICTION',
    'FIGHTER','FINALLY','FINANCE','FINDING','FITNESS','FOREIGN','FOREVER','FORMULA',
    'FORTUNE','FORWARD','FOUNDER','FREEDOM','FREIGHT','FULFILL','FUNERAL','FURNISH',
    'FURTHER','GALLERY','GATEWAY','GENERAL','GENETIC','GENUINE','GESTURE','GETTING',
    'GLIMPSE','GRABBER','GRANDMA','GRANITE','GRAPHIC','GRAVITY','GREATER','GROCERY',
    'GROWING','HABITAT','HALFWAY','HANDLER','HANDFUL','HAPPILY','HARBOUR','HARMONY',
    'HARVEST','HEADING','HEALTHY','HEARING','HEAVILY','HELPFUL','HERSELF','HIGHWAY',
    'HIMSELF','HISTORY','HOLDING','HOLIDAY','HONORED','HOUSING','HOWEVER','HUNDRED',
    'HUNTING','HUSBAND','ILLEGAL','IMAGINE','IMMENSE','IMPLIED','IMPROVE','INCLUDE',
    'INDEXED','INITIAL','INSIGHT','INSPECT','INSTALL','INSTANT','INSTEAD','INTENSE',
    'INTERIM','INVALID','INVOLVE','ISOLATE','JOINTLY','JOURNAL','JOURNEY','JUSTICE',
    'JUSTIFY','KEEPING','KINGDOM','KITCHEN','KNOWING','LABELED','LACKING','LANDING',
    'LARGELY','LASTING','LATERAL','LEADING','LEAFLET','LEARNED','LEATHER','LENDING',
    'LIBERAL','LIBERTY','LIBRARY','LICENCE','LIMITED','LINKING','LISTING','LITERAL',
    'LOGICAL','LONG','LOTTERY','LOYALTY','LUGGAGE','MACHINE','MARRIED','MASSIVE',
    'MASTERY','MATURED','MAXIMUM','MEASURE','MEETING','MENTION','MINERAL','MINIMUM',
    'MISSING','MISSION','MIXTURE','MODULAR','MONITOR','MONTHLY','MORNING','MYSTERY',
    'NATURAL','NEITHER','NERVOUS','NETWORK','NEUTRAL','NOTABLE','NOTHING','NUCLEAR',
    'NURSING','OBESITY','OBJECTS','OFFENSE','OFFICER','ONGOING','OPERATE','OPINION',
    'OPTIMAL','ORGANIC','ORIGINS','OUTCOME','OUTDOOR','OUTLOOK','OVERALL','OVERLAP',
    'OVERSEE','PACKAGE','PAINFUL','PAINTED','PARKING','PARTIAL','PARTNER','PASSAGE',
    'PASSING','PASSION','PASSIVE','PATIENT','PATRIOT','PATTERN','PAYMENT','PENALTY',
    'PENDING','PENSION','PERCENT','PERFECT','PERFORM','PERHAPS','PERSIST','PITCHER',
    'PLACING','PLANNED','PLANNER','PLASTIC','PLATOON','PLAYING','POINTED','POLITIC',
    'POPULAR','PORTION','POVERTY','PREDICT','PREPARE','PRESENT','PREVENT','PRIMARY',
    'PRINTER','PRIVACY','PRIVATE','PROBLEM','PROCEED','PROCESS','PRODUCE','PRODUCT',
    'PROFILE','PROGRAM','PROJECT','PROMISE','PROMOTE','PROPOSE','PROSPER','PROTECT',
    'PROTEST','PROVIDE','PUBLISH','PURPOSE','PURSUIT','QUALIFY','QUARTER','QUIETLY',
    'RADICAL','RAILWAY','RAISING','RAPIDLY','READILY','READING','REALITY','REALIZE',
    'REBUILD','RECEIVE','RECOVER','RECRUIT','REDUCED','REFLECT','REFUGEE','REGULAR',
    'RELATED','RELEASE','REMAINS','RENEWAL','REPLIED','REQUIRE','RESERVE','RESOLVE',
    'RESPECT','RESPOND','RESTORE','RETIRED','RETREAT','RETURNS','REVENUE','REVERSE',
    'REVISED','REVIVAL','REVOLVE','ROBBERY','ROLLING','ROUTINE','ROYALTY','RUNNING',
    'SALVAGE','SANCTION','SCANDAL','SCATTER','SCENERY','SCHOLAR','SCIENCE','SECTION',
    'SEGMENT','SEMINAR','SERVICE','SESSION','SETTING','SEVENTH','SEVERAL','SHELTER',
    'SHIFTED','SHIPPIN','SHOCKED','SHORTER','SHORTLY','SHOWING','SILENCE','SILICON',
    'SIMILAR','SINCERE','SITTING','SKILLED','SLAVERY','SMALLER','SMOKING','SOCIETY',
    'SOLDIER','SOLVING','SOMEHOW','SPEAKER','SPECIAL','SPONSOR','SPOTTED','SQUEEZE',
    'STAGGER','STARTUP','STATION','STORAGE','STRANGE','STRETCH','STUDENT','SUBSIDY',
    'SUCCESS','SUGGEST','SUMMARY','SUPPORT','SUPREME','SURFACE','SURGEON','SURPLUS',
    'SURNAME','SURVIVE','SUSPECT','SUSPEND','TACTICS','TEACHER','TENSION','TEXTILE',
    'THEATER','THEATRE','THERAPY','THEREBY','THOUGHT','THROUGH','TONIGHT','TOTALLY',
    'TOURISM','TOURIST','TRACKER','TRADING','TRAFFIC','TRAINER','TROUBLE','TRUSTED',
    'TURNING','TYPICAL','UNIFIED','UNIFORM','UNKNOWN','UNUSUAL','UPGRADE','UPRIGHT',
    'UTILITY','VACANCY','VACCINE','VARIANT','VARIETY','VEHICLE','VENTURE','VERSION',
    'VETERAN','VICTORY','VILLAGE','VINTAGE','VIOLENT','VIRTUAL','VISITOR','VOLTAGE',
    'WAITING','WARNING','WARRANT','WASHING','WEATHER','WEBINAR','WEBMAIL','WEBSITE',
    'WEDDING','WEEKEND','WELFARE','WESTERN','WHETHER','WHOEVER','WILLING','WINNING',
    'WITNESS','WORKING','WRAPPER','WRITING','WRITTEN','YOUNGER'
];

// 8-letter words
const WORDS_8 = [
    'ABSOLUTE','ABSTRACT','ACADEMIC','ACCEPTED','ACCIDENT','ACCURATE','ACHIEVED','ACTIVATE',
    'ACTUALLY','ADDITION','ADEQUATE','ADJACENT','ADJUSTED','ADMITTED','ADVANCED','ADVOCAT',
    'AFFECTED','AFFORDED','AIRCRAFT','ALLIANCE','ALTHOUGH','AMBITION','ANALYSIS','ANCESTOR',
    'ANIMATED','ANNOUNCE','ANYTHING','ANYWHERE','APPETITE','APPLAUSE','APPROVAL','ASSESSED',
    'ASSUMING','ASSURING','ATTACHED','ATTORNEY','AUDIENCE','AUTHORED','AVIATION','BACHELOR',
    'BACKWARD','BALANCED','BANKRUPT','BASELINE','BATHROOM','BECOMING','BEHAVIOR','BIRTHDAY',
    'BLEEDING','BLOCKING','BOLDNESS','BOOKMARK','BOUNDARY','BREAKING','BREEDING','BRIEFING',
    'BRINGING','BROWSING','BUILDING','BULLETIN','BUSINESS','CALENDAR','CAMPAIGN','CANNABIS',
    'CAPACITY','CARRIAGE','CASUALTY','CATCHING','CATERING','CAUTIOUS','CEREMONY','CHAIRMAN',
    'CHAMPION','CHANGING','CHAPTERS','CHARGING','CHEMICAL','CHILDREN','CHOOSING','CITATION',
    'CIVILIAN','CLIMBING','CLINICAL','COACHING','COHERENT','COLLAPSE','COLONIAL','COMEBACK',
    'COMMERCE','COMMONLY','COMMUNAL','COMPARED','COMPILED','COMPLETE','COMPOUND','COMPUTER',
    'CONCLUDE','CONCRETE','CONFLICT','CONGRESS','CONSIDER','CONSTANT','CONSUMER','CONTAINS',
    'CONTINUE','CONTRACT','CONTRAST','CONTROLS','CONVERGE','CONVINCE','CORRIDOR','COVERING',
    'CREATIVE','CRIMINAL','CRITICAL','CROSSING','CRUSHING','CULTURAL','CURRENCY','CUSTOMER',
    'DATABASE','DEADLINE','DECEMBER','DECIDING','DECISION','DECLARED','DECLINED','DECREASE',
    'DEDICATE','DEEPENED','DEFENDER','DEFINITE','DELICATE','DELIVERY','DEMANDED','DESIGNER',
    'DETECTED','DEVELOP','DIALOGUE','DIRECTED','DIRECTOR','DISABLED','DISCOUNT','DISCOVER',
    'DISORDER','DISPATCH','DISTINCT','DIVISION','DOCTRINE','DOCUMENT','DOMESTIC','DOMINANT',
    'DONATION','DOUBTFUL','DRAMATIC','DRILLING','DROPPING','DURATION','DWELLING','DYNAMICS',
    'EARNINGS','ECONOMIC','EDUCATED','ELECTION','ELECTRIC','ELEVATED','ELIGIBLE','EMERGING',
    'EMISSION','EMPHASIS','EMPLOYED','EMPLOYEE','EMPLOYER','ENCLOSED','ENCODING','ENORMOUS',
    'ENROLLED','ENSURING','ENTIRELY','ENTRANCE','ENVELOPE','EQUIPPED','ESTIMATE','EVALUATE',
    'EVENTUAL','EVERYONE','EVIDENCE','EXCHANGE','EXCITING','EXCLUDED','EXERCISE','EXISTING',
    'EXPANDED','EXPECTED','EXPEDITE','EXPLICIT','EXPONENT','EXPOSURE','EXTENDED','EXTERNAL',
    'ENORMOUS','FACILITY','FAMILIAR','FAMILIES','FAVORITE','FEASIBLE','FEATURED','FEEDBACK',
    'FESTIVAL','FIGHTING','FILENAME','FILMFARE','FILEPATH','FILTERED','FINALIZE','FINALIST',
    'FINANCED','FINDINGS','FINISHED','FLAGSHIP','FLEXIBLE','FLOATING','FOLLOWED','FOLLOWER',
    'FOOTWEAR','FORCEFUL','FORECAST','FORMERLY','FOURTEEN','FRACTION','FRAGMENT','FREQUENT',
    'FRIENDLY','FRONTIER','FULLBACK','FULLTIME','FUNCTION','GAMBLING','GATHERED','GENERATE',
    'GENEROUS','GENOCIDE','GRADIENT','GRADUATE','GRAPHICS','GRATEFUL','GREATEST','GUARDIAN',
    'GUIDANCE','HANDLING','HAPPENED','HARDWARE','HEADLINE','HELPLESS','HERITAGE','HOMEPAGE',
    'HOMELESS','HOMEWORK','HONESTLY','HOSPITAL','HUMANITY','HUMILITY','HYDROGEN','IDENTIFY',
    'IDEOLOGY','ILLUSION','IMAGINED','IMMINENT','IMMUNITY','IMPERIAL','IMPLICIT','IMPORTED',
    'IMPROVED','INCIDENT','INCLUDED','INCREASE','INDICATE','INDIRECT','INDUSTRY','INFANTRY',
    'INFERIOR','INFINITE','INFORMAL','INFORMED','INFRARED','INHERENT','INITIATE','INNOCENT',
    'INSPIRED','INSTANCE','INTEGRAL','INTENDED','INTERACT','INTEREST','INTERIOR','INTERNAL',
    'INTERVAL','INTIMATE','INVASION','INVESTOR','INVOLVED','ISOLATED','JUDGMENT','JUNCTION',
    'KEYBOARD','LANDMARK','LANGUAGE','LAUNCHED','LAWFULLY','LEARNING','LEFTOVER','LEVERAGE',
    'LIFESPAN','LIFETIME','LIKENESS','LIMITING','LISTENER','LITERARY','LITIGANT','LONGTERM',
    'MAGAZINE','MAGNETIC','MAJORITY','MANAGING','MANIFEST','MEASURED','MECHANIC','MEDICINE',
    'MEMORIAL','MERCHANT','MIDNIGHT','MILITARY','MINERALS','MINISTER','MINORITY','MODERATE',
    'MODIFIED','MOISTURE','MOLECULE','MOMENTUM','MONETARY','MORTGAGE','MOVEMENT','MULTIPLE',
    'MULTIPLY','MUTATION','NATIONAL','NAVIGATE','NEGATIVE','NEIGHBOR','NORMALLY','NORTHERN',
    'NOTEBOOK','NOVEMBER','NUMEROUS','OBJECTED','OBSERVED','OBSERVER','OBTAINED','OCCASION',
    'OCCURRED','DECEMBER','OFFERING','OFFICIAL','OFFSHORE','TOMORROW','OPPONENT','OPPOSING',
    'OPPOSITE','ORDINARY','ORIGINAL','OUTBREAK','OUTLINED','OVERCOME','OVERHEAD','OVERLOOK',
    'OVERSEAS','OVERVIEW','PAINTING','PARALLEL','PEACEFUL','PECULIAR','PERSONAL','PETITION',
    'PIPELINE','PLATFORM','PLEASANT','PLEASURE','PLENTFUL','POINTING','POLISHED','POLITICS',
    'POPULACE','POPULISM','PORTRAIT','POSITION','POSITIVE','POSSIBLY','POWERFUL','PRACTICE',
    'PRECIOUS','PREGNANT','PREMISES','PREPARED','PRESENCE','PRESERVE','PRESSING','PRESTIGE',
    'PREVIOUS','PRINCESS','PRINTING','PRIORITY','PRISONER','PROBABLY','PRODUCED','PRODUCER',
    'PROFOUND','PROGRESS','PROJECTS','PROMISED','PROMPTED','PROPERLY','PROPERTY','PROPOSAL',
    'PROPOSED','PROSPECT','PROTOCOL','PROVIDED','PROVIDER','PROVINCE','PUBLICLY','PURCHASE',
    'PURSUING','QUARTERS','QUESTION','REACTION','READABLE','RECEIVED','RECENTLY','RECKONED',
    'RECORDER','RECOVERY','REDUCING','REFERRAL','REFERRED','REFLECTS','REGIONAL','REGISTER',
    'REGULATE','RELATION','RELATIVE','RELAXING','RELEASED','RELEVANT','RELIANCE','RELIGION',
    'REMAINED','REMEMBER','REMOVING','RENOWNED','REPEATED','REPLACED','REPORTED','REPORTER',
    'REPUBLIC','RESEARCH','RESERVED','RESIDENT','RESIGNED','RESOLVED','RESOURCE','RESPONSE',
    'RESTORED','RESTRAIN','RESTRICT','RESULTED','RETAINED','RETIRING','RETRIEVE','REVEALED',
    'REVIEWED','REVIEWER','REVISION','RIGOROUS','ROMANTIC','SAMPLING','SANCTION','SANDWICH',
    'SCENARIO','SCHEDULE','SEASONAL','SECONDLY','SECURITY','SELECTED','SEMESTER','SENTENCE',
    'SEPARATE','SEQUENCE','SERGEANT','SEVERELY','SHIPPING','SHOOTING','SHOPPING','SHORTAGE',
    'SHOULDER','SIDEWAYS','SIMPLIFY','SIMULATE','SITUATED','SKELETON','SLIPPERY','SMALLEST',
    'SNAPSHOT','SOFTWARE','SOMEBODY','SOUTHERN','SPECIFIC','SPENDING','SPECTRUM','SPIRITED',
    'SPORTING','SPOTLESS','STAGNANT','STANDARD','STANDING','STARTING','STEALING','STEPPING',
    'STIMULUS','STOPPING','STRAIGHT','STRANGER','STRATEGY','STRENGTH','STRICTLY','STRIKING',
    'STRONGLY','STRUGGLE','STUNNING','SURPRISE','SURROUND','SURVIVAL','SURVIVED','SURVIVOR',
    'SUPPOSED','SYMPTOMS','TEACHING','TEAMWORK','TERMINAL','TERRIFIC','TEXTBOOK','THINKING',
    'THIRTEEN','THOROUGH','THOUSAND','TIMELINE','TOLERANT','TOMORROW','TRACKING','TRAINING',
    'TRANSFER','TREASURE','TREATING','TRILLION','TROPICAL','TROUBLED','TRUTHFUL','TUTORING',
    'ULTIMATE','UMBRELLA','UNDERWAY','UNIVERSE','UNLAWFUL','UNLIKELY','UNSTABLE','UPDATING',
    'UPCOMING','UPHEAVAL','VACATION','VALUABLE','VARIABLE','VEHICLES','VERTICAL','VICTORIA',
    'VIOLATED','VIOLENCE','VIRGINIA','VISITING','VOLATILE','WEAKNESS','WHENEVER','WHEREVER',
    'WILDLIFE','WIRELESS','WITHDRAW','WOODLAND','WORKSHOP','YOURSELF'
];

// Combine all words into a master list keyed by length
const ALL_WORDS = {};
WORDS_4.forEach(w => { (ALL_WORDS[4] = ALL_WORDS[4] || []).push(w); });
WORDS_5.forEach(w => { (ALL_WORDS[5] = ALL_WORDS[5] || []).push(w); });
WORDS_6.forEach(w => { (ALL_WORDS[6] = ALL_WORDS[6] || []).push(w); });
WORDS_7.forEach(w => { (ALL_WORDS[7] = ALL_WORDS[7] || []).push(w); });
WORDS_8.forEach(w => { (ALL_WORDS[8] = ALL_WORDS[8] || []).push(w); });

// Legacy alias for backward compatibility
const ANSWER_WORDS = WORDS_5;

// Get filtered word list for a difficulty tier
function getWordsForDifficulty(difficulty) {
    const tier = DIFFICULTY_TIERS[difficulty] || DIFFICULTY_TIERS.normal;
    let words = [];
    for (let len = tier.minLen; len <= tier.maxLen; len++) {
        if (ALL_WORDS[len]) words = words.concat(ALL_WORDS[len]);
    }
    // Fallback: if no words found, use 5-letter words
    return words.length > 0 ? words : WORDS_5;
}

// Local cache for API-validated words (valid = true, invalid = false)
const _wordCache = {};
// Pre-populate cache with all word lists
[WORDS_4, WORDS_5, WORDS_6, WORDS_7, WORDS_8].forEach(list => {
    list.forEach(w => { _wordCache[w] = true; });
});

// Validate word via Free Dictionary API
async function _checkDictionaryAPI(word) {
    try {
        const res = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word.toLowerCase()}`);
        return res.ok;
    } catch {
        // Network error: accept the word to avoid blocking gameplay
        return true;
    }
}

// Current expected word length (set by game init)
let _expectedWordLength = 5;

// Async word validation: checks cache first, then API
async function isValidWordAsync(word) {
    const upper = word.toUpperCase();
    if (upper.length !== _expectedWordLength) return false;

    // Check cache
    if (_wordCache[upper] !== undefined) {
        return _wordCache[upper];
    }

    // Check API
    const valid = await _checkDictionaryAPI(upper);
    _wordCache[upper] = valid;
    return valid;
}

// Sync fallback (for backward compatibility) - checks cache only
function isValidWord(word) {
    const upper = word.toUpperCase();
    if (upper.length !== _expectedWordLength) return false;
    // Cache hit
    if (_wordCache[upper] !== undefined) return _wordCache[upper];
    // Not in cache = unknown, accept optimistically (API will validate later)
    return true;
}

// Get word of the day based on date (supports difficulty)
function getWordOfTheDay(difficulty) {
    const words = getWordsForDifficulty(difficulty || 'normal');
    const today = new Date();
    const startDate = new Date(2024, 0, 1);
    const dayIndex = Math.floor((today - startDate) / (1000 * 60 * 60 * 24)) % words.length;
    return words[dayIndex];
}

// Get a random word for practice mode (supports difficulty)
function getRandomWord(difficulty) {
    const words = getWordsForDifficulty(difficulty || 'normal');
    return words[Math.floor(Math.random() * words.length)];
}
